name: CICD PIPELINE

on:
    workflow_dispatch: 
        inputs:
            environment:
                description: 'Executed based on env selected'
                required: true
                default: dev
                type: choice
                options:
                    - dev
                    - qa
                    - prod

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: set environment variables
              run : |
                if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
                echo Environment": ${{ inputs.environment }}" >> "$GITHUB_ENV"
                echo "The environment variable Environment is: $Environment"
                elif [ "${{ github.event.inputs.environment }}" == "qa" ]; then
                echo "Environment: ${{ inputs.environment }}" >> "$GITHUB_ENV"
                echo "The environment variable Environment is: $Environment"
                elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
                echo "Environment: ${{ inputs.environment }}" >> "$GITHUB_ENV"
                echo "The environment variable Environment is: $Environment"
                fi

        
