name: CICD PIPELINE

on:
    workflow_dispatch: 
        inputs:
            environment:
                description: 'Executed based on env selected'
                required: true
                default: dev
                type: choice
                options:
                    - dev
                    - qa
                    - prod

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: set environment variables
              run : |
                echo "Environment: ${{ inputs.environment }}" >> "$GITHUB_ENV"
            - name: use the environment variable
              run: |
                printf '%s\n' "$Environment"
